include ./themes/Dark_Pastel.conf

font_size 11
modify_font cell_height 100%
window_margin_width 4
draw_minimal_borders yes
window_border_width 0
background_opacity 0.8

map super+shift+enter launch --type=os-window --cwd=current
